workflows:
  ios-capacitor-workflow:
    name: Build iOS App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install dependencies
        script: | 
          npm install --legacy-peer-deps
      - name: Build Web Project
        script: | 
          npm run build
      - name: Capacitor Sync
        script: | 
          npx cap sync ios
      - name: Build iOS (.ipa)
        script: | 
          xcode-project build-ipa --workspace $XCODE_WORKSPACE --scheme $XCODE_SCHEME
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - TU_EMAIL_pacocasadoc@gmail.com